CC = gcc
CFLAGS = -Wall -Wextra -I./include
TARGET = program
SRC_DIR = labs
SRC_FILES = $(SRC_DIR)/main.c $(SRC_DIR)/lab1.c $(SRC_DIR)/lab2.c $(SRC_DIR)/lab3.c $(SRC_DIR)/lab4.c
OBJ_FILES = $(SRC_FILES:.c=.o)

all: $(TARGET)

$(TARGET): $(OBJ_FILES)
	$(CC) $(OBJ_FILES) -o $(TARGET)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJ_FILES) $(TARGET)

run: $(TARGET)
	./$(TARGET)

.PHONY: all clean run